### ISSUE TITLE
ConvertStringToFloat code and tooltip improvment suggestions

### ISSUE THREAD

**Issue by jeanfabre** [jeanfabre/PlayMakerCustomActions_U3#3]
Hi,
 
ConvertStringToFloat.cs the tooltip for the fsmFloat is still from the original action ( mention int), as well as the method which still mention Int as well.

Bye,

 Jean

**Comment by djaydino** [comment]
Hi, i have updated the action
thx

greetings,

Dino

**Comment by jeanfabre** [comment]
Excellent, thanks! also, be aware that there is an existing action on this:

https://github.com/jeanfabre/PlayMakerCustomActions_U3/blob/master/Assets/PlayMaker%20Custom%20Actions/Convert/ConvertFormatedStringToFloat.cs

Your action is totally fine, let's keep it, but  being able to specify the format increase the flexibility.

https://msdn.microsoft.com/en-us/library/system.globalization.numberstyles(v=vs.110).aspx

Bye,

 Jean

**Comment by djaydino** [comment]
i must have overlooked that action :)

as i was thinking the name would be same as convert string to int, but then float instead of int.

**Comment by jeanfabre** [comment]
Usually, when I want to verify if an action exists, I only type the few keywords like "convert float", which gives more chances to catch an similar action. There are so much actions now available :)
